# Data Manipulation Studio

For this studio, we will revisit our California farmers looking for advice on growing pumpkins and the same [pumpkins dataset](https://www.kaggle.com/usda/a-year-of-pumpkin-prices) as provided by the U.S. Department of Agriculture. You may have to clean data in the process of data manipulation, so feel free to pull up your notebook from the last class's studio.

We will now be focusing our attention on a different region in the United States, the Northeast. When you open up the `dataset` folder, you will have 13 CSVs, including the San Francisco and Los Angeles data from the last lesson. The 13 CSVs are each a different terminal market in the United States.

## Getting Started

Import the CSVs for each of the following cities: Baltimore, Boston, New York, and Philadelphia. Set up a dataframe for each city.

In [5]:
# Import the necessary libraries and CSVs. Make some dataframes!
import pandas as pd
import numpy as np
import matplotlib as plt

In [31]:
df_blt = pd.read_csv('dataset/baltimore_9-24-2016_9-30-2017.csv')
df_bos = pd.read_csv('dataset/boston_9-24-2016_9-30-2017.csv')
df_phi = pd.read_csv('dataset/philadelphia_9-24-2016_9-30-2017.csv')
df_ny = pd.read_csv('dataset/new-york_9-24-2016_9-30-2017.csv')

## Clean Your Data

In the last lesson, we cleaned the data to related to San Francisco. Pull up your notebook from the last lesson and use your cleaning skills to clean the dataframes as necessary.

In [32]:
# Clean your data here!
df_ny.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,130,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,130,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,120,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [33]:
df_blt.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,04/29/2017,270,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN
1,PUMPKINS,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,05/06/2017,270,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN
2,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,11/05/2016,90,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [34]:
df_bos.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,180,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [35]:
df_phi.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/16/2017,140,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/01/2016,140,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [37]:
df_ny.duplicated(subset=None, keep='first')

0      False
1      False
2      False
3      False
4      False
       ...
107    False
108    False
109    False
110    False
111    False
Length: 112, dtype: bool

In [38]:
df_blt.duplicated(subset=None, keep='first')

0      False
1      False
2      False
3      False
4      False
       ...
148    False
149    False
150    False
151    False
152    False
Length: 153, dtype: bool

In [39]:
df_bos.duplicated(subset=None, keep='first')

0      False
1      False
2      False
3      False
4      False
       ...
347    False
348    False
349    False
350    False
351    False
Length: 352, dtype: bool

In [40]:
df_phi.duplicated(subset=None, keep='first')

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
dtype: bool

In [41]:
df_ny.drop_duplicates()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,130,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,130,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,120,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,PUMPKINS,NEW YORK,NaN,bushel cartons,MINIATURE,NaN,NaN,09/09/2017,32,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
108,PUMPKINS,NEW YORK,NaN,1 1/9 bushel crates,MINIATURE,ROUND TYPE,NaN,10/08/2016,18,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
109,PUMPKINS,NEW YORK,NaN,1 1/9 bushel crates,MINIATURE,ROUND TYPE,NaN,10/08/2016,18,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
110,PUMPKINS,NEW YORK,NaN,1 1/9 bushel crates,MINIATURE,ROUND TYPE,NaN,10/15/2016,18,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
111,PUMPKINS,NEW YORK,NaN,1 1/9 bushel crates,MINIATURE,ROUND TYPE,NaN,10/15/2016,18,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [42]:
df_blt.drop_duplicates()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,04/29/2017,270,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN
1,PUMPKINS,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,05/06/2017,270,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN
2,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,11/05/2016,90,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,PUMPKINS,BALTIMORE,NaN,1/2 bushel cartons,MINIATURE,NaN,NaN,09/30/2017,18,18.0,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
149,PUMPKINS,BALTIMORE,NaN,1/2 bushel cartons,MINIATURE,NaN,NaN,09/30/2017,18,18.0,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
150,PUMPKINS,BALTIMORE,NaN,1/2 bushel cartons,MINIATURE,ROUND TYPE,NaN,09/24/2016,15,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
151,PUMPKINS,BALTIMORE,NaN,1/2 bushel cartons,MINIATURE,ROUND TYPE,NaN,10/01/2016,15,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
152,PUMPKINS,BALTIMORE,NaN,1/2 bushel cartons,MINIATURE,ROUND TYPE,NaN,10/08/2016,15,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [43]:
df_bos.drop_duplicates()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,200,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,180,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,PUMPKINS,BOSTON,NaN,1/2 bushel cartons,MINIATURE,ROUND TYPE,NaN,10/22/2016,15,18,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
348,PUMPKINS,BOSTON,NaN,1/2 bushel cartons,MINIATURE,ROUND TYPE,NaN,10/29/2016,15,18,...,WHITE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
349,PUMPKINS,BOSTON,NaN,1/2 bushel cartons,MINIATURE,ROUND TYPE,NaN,10/29/2016,15,18,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
350,PUMPKINS,BOSTON,NaN,1/2 bushel cartons,MINIATURE,ROUND TYPE,NaN,11/05/2016,15,18,...,WHITE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
351,PUMPKINS,BOSTON,NaN,1/2 bushel cartons,MINIATURE,ROUND TYPE,NaN,11/05/2016,15,18,...,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [44]:
df_phi.drop_duplicates()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/16/2017,140,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/01/2016,140,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
5,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/01/2016,140,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
6,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/01/2016,120,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
7,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/08/2016,140,155,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
8,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/08/2016,120,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
9,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/15/2016,120,125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
10,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/15/2016,100,125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
11,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/22/2016,130,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
12,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/22/2016,120,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
13,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/22/2016,130,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
14,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/22/2016,100,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
15,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/29/2016,130,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
16,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/29/2016,120,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
17,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/29/2016,130,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
18,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,10/29/2016,100,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
19,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/16/2017,120,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
20,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/16/2017,120,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
21,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/23/2017,140,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
22,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/23/2017,150,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
23,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/23/2017,120,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
24,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/23/2017,140,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
25,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/23/2017,140,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
26,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/30/2017,140,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
27,PUMPKINS,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/30/2017,140,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
28,PUMPKINS,PHILADELPHIA,NaN,1 1/9 bushel cartons,PIE TYPE,NaN,NaN,10/15/2016,12,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
29,PUMPKINS,PHILADELPHIA,NaN,1 1/9 bushel cartons,PIE TYPE,NaN,NaN,10/22/2016,12,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
30,PUMPKINS,PHILADELPHIA,NaN,1 1/9 bushel cartons,PIE TYPE,NaN,NaN,10/29/2016,12,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
31,PUMPKINS,PHILADELPHIA,NaN,1 1/9 bushel cartons,PIE TYPE,NaN,NaN,08/26/2017,18,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
32,PUMPKINS,PHILADELPHIA,NaN,1 1/9 bushel cartons,PIE TYPE,NaN,NaN,09/16/2017,18,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
33,PUMPKINS,PHILADELPHIA,NaN,1 1/9 bushel cartons,PIE TYPE,NaN,NaN,09/23/2017,18,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
34,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,NaN,NaN,10/01/2016,250,250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
35,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,NaN,NaN,10/15/2016,140,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
36,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,NaN,NaN,10/22/2016,140,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
37,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,NaN,NaN,10/22/2016,75,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
38,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,NaN,NaN,10/29/2016,140,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
39,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,NaN,NaN,10/29/2016,75,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
40,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,NaN,NaN,09/23/2017,180,180,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
41,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,NaN,NaN,09/23/2017,140,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
42,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,NaN,NaN,09/23/2017,180,180,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
43,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,NaN,NaN,09/30/2017,140,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
44,PUMPKINS,PHILADELPHIA,NaN,24 inch bins,KNUCKLE HEAD,NaN,NaN,10/08/2016,210,210,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
45,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,09/24/2016,17,18,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
46,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,10/01/2016,18,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
47,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,10/01/2016,17,18,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
48,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,10/08/2016,15,15,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
49,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,10/15/2016,15,18,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
50,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,10/22/2016,16,18,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
51,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,10/29/2016,16,18,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
52,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,11/05/2016,16,18,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
53,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,08/26/2017,18,20,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
54,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,09/16/2017,16,16,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
55,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,09/23/2017,15,16,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
56,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,09/30/2017,15,18,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN

## Combine Your Data

Now that you have four clean sets of data, combine all four into one dataframe that represents the entire Northeast region.

In [49]:
# Combine the four dataframes into one!
neregion = pd.concat([df_blt, df_bos, df_phi, df_ny], axis=0)

## Answer Some Questions

Use `groupby()` and `agg()` to answer the following two questions:

1. What is the mean low and high prices for each type of unit of sale in the Northeast region? In the last lesson, we learned that a unit of sale could be something like a bin or individually. 
2. What is the average number of pumpkins for each variety that came into terminal markets for the year by region? Pumpkin varieties include Howden and Fairytale pumpkins.

In [52]:
# Put your code here to find the mean low and high prices in the Northeast region for each type of unit of sale.
neregion_unit_sales = neregion.groupby('Unit of Sale')
neregion_unit_sales.first()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Item Size,Color,Environment,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
Unit of Sale,,,,,,,,,,,,,,,,,,,,,
EACH,PUMPKINS,BALTIMORE,NaN,24 inch bins,BIG MACK TYPE,None,NaN,09/24/2016,50,60.0,...,jbo,WHITE,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
PER BIN,PUMPKINS,BOSTON,NaN,36 inch bins,HOWDEN TYPE,None,NaN,09/23/2017,200,225.0,...,jbo,ORANGE,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
SHELLACKED,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,09/24/2016,17,18.0,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [56]:
#neregion_unit_sales.agg("mean", axis="columns")

neregion_unit_sales.agg({'Low Price' : ['min', 'max'], 'High Price' : ['min', 'max']})

             Low Price      High Price
                   min  max        min    max
Unit of Sale
EACH                40   50       50.0   60.0
PER BIN            120  300      140.0  300.0
SHELLACKED          15   18       15.0   20.0

In [59]:
# Put your code here to find the average number of pumpkins coming into terminal markets of each variety.
neregion_number_pumpkins = neregion.groupby('Variety')
neregion_number_pumpkins.first()

,Commodity Name,City Name,Type,Package,Sub Variety,Grade,Date,Low Price,High Price,Mostly Low,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
Variety,,,,,,,,,,,,,,,,,,,,,
BIG MACK TYPE,PUMPKINS,BALTIMORE,NaN,24 inch bins,None,NaN,09/24/2016,50,60.0,50,...,WHITE,NaN,EACH,NaN,NaN,NaN,NaN,NaN,N,NaN
BLUE TYPE,PUMPKINS,BOSTON,NaN,24 inch bins,None,NaN,09/24/2016,260,285.0,285,...,ORANGE,NaN,None,NaN,NaN,NaN,NaN,NaN,N,NaN
CINDERELLA,PUMPKINS,BALTIMORE,NaN,24 inch bins,None,NaN,06/03/2017,380,380.0,380,...,ORANGE,NaN,None,NaN,NaN,NaN,NaN,NaN,E,NaN
FAIRYTALE,PUMPKINS,BALTIMORE,NaN,24 inch bins,None,NaN,09/24/2016,250,260.0,250,...,ORANGE,NaN,None,NaN,NaN,NaN,NaN,NaN,N,NaN
HOWDEN TYPE,PUMPKINS,BALTIMORE,NaN,24 inch bins,None,NaN,09/24/2016,160,160.0,160,...,ORANGE,NaN,PER BIN,NaN,NaN,NaN,NaN,NaN,N,NaN
HOWDEN WHITE TYPE,PUMPKINS,BALTIMORE,NaN,24 inch bins,None,NaN,09/23/2017,160,180.0,160,...,None,NaN,None,NaN,NaN,NaN,NaN,NaN,N,NaN
KNUCKLE HEAD,PUMPKINS,BOSTON,NaN,24 inch bins,None,NaN,09/24/2016,260,285.0,285,...,ORANGE,NaN,None,NaN,NaN,NaN,NaN,NaN,N,NaN
MINIATURE,PUMPKINS,BALTIMORE,NaN,1/2 bushel cartons,FLAT TYPE,NaN,09/24/2016,18,18.0,18,...,WHITE,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
MIXED HEIRLOOM VARIETIES,PUMPKINS,BALTIMORE,NaN,24 inch bins,None,NaN,09/16/2017,160,240.0,160,...,None,NaN,None,NaN,NaN,NaN,NaN,NaN,N,NaN
PIE TYPE,PUMPKINS,BALTIMORE,NaN,1 1/9 bushel cartons,None,NaN,09/24/2016,15,15.0,15,...,ORANGE,NaN,PER BIN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [105]:
neregion_number_pumpkins.mean('Unit of Sale')

,Type,Grade,Low Price,High Price,Mostly Low,Mostly High,Environment,Quality,Condition,Appearance,Storage,Crop,Trans Mode
City Name,,,,,,,,,,,,,
BALTIMORE,NaN,NaN,101.490196,109.055556,101.490196,108.859477,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BOSTON,NaN,NaN,162.840909,187.235795,172.721591,176.130682,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NEW YORK,NaN,NaN,107.125000,116.482143,107.312500,116.410714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PHILADELPHIA,NaN,NaN,98.140351,103.754386,98.491228,103.754386,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Bonus Mission

Try answering the same questions for the Midwest (Chicago, Detroit, and St. Louis) or the Southeast (Atlanta, Columbia, and Miami) regions.

In [59]:
# Try the bonus mission if you have time!